sudo: required
dist: trusty

language: cpp
compiler:
  - clang

git:
  depth: 1

before_install:
  - sudo apt-get -qq install build-essential libtool make cmake cmake-data openssl
  - sudo apt-get -qq install libssl-dev libreadline6-dev zlib1g-dev libbz2-dev
  - git config user.email "travis@build.bot" && git config user.name "Travis CI"
  - git tag -a -m "Travis build" init

install:
  - cmake
  - make -j 8 -k && make install