sudo: required
dist: trusty

language: cpp
compiler:
  - clang

git:
  depth: 1

before_install:
  - sudo apt-get -qq install build-essential libtool make cmake cmake-data openssl
  - sudo apt-get -qq install libssl-dev libmysqlclient-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev
  - sudo apt-get -qq install libboost1.55-dev libboost-thread1.55-dev libboost-filesystem1.55-dev libboost-system1.55-dev libboost-program-options1.55-dev libboost-iostreams1.55-dev
  - sudo apt-get -qq install mysql-server
  - git config user.email "travis@build.bot" && git config user.name "Travis CI"
  - git tag -a -m "Travis build" init

install:
  - configure && make && make test