version: 1.0.{build}
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
before_build:
  - cmd: SET PATH=%APPVEYOR_BUILD_FOLDER%\Noggit3libs;%PATH%
  - ps: cmake -G "Visual Studio 14"
build:
  project: Noggit.sln
  verbosity: normal
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))